### ISSUE TITLE
Empty YML files result in AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by stumelius** [dbt-checkpoint/dbt-checkpoint#30]
**Describe the bug**
Empty YML files result in `AttributeError: 'NoneType' object has no attribute 'get'` when running `check-source-table-has-description` hook.

```
Traceback (most recent call last):
  File "/home/simo/.cache/pre-commit/repohg6wkw_k/py_env-python3.8/bin/check-source-table-has-description", line 8, in <module>
    sys.exit(main())
  File "/home/simo/.cache/pre-commit/repohg6wkw_k/py_env-python3.8/lib/python3.8/site-packages/pre_commit_dbt/check_source_table_has_description.py", line 33, in main
    return has_description(paths=args.filenames)
  File "/home/simo/.cache/pre-commit/repohg6wkw_k/py_env-python3.8/lib/python3.8/site-packages/pre_commit_dbt/check_source_table_has_description.py", line 17, in has_description
    for schema in schemas:
  File "/home/simo/.cache/pre-commit/repohg6wkw_k/py_env-python3.8/lib/python3.8/site-packages/pre_commit_dbt/utils.py", line 210, in get_source_schemas
    for source in schema.get("sources", []):
AttributeError: 'NoneType' object has no attribute 'get'
```

**To Reproduce**
1. Create an empty .yml file in your dbt project
2. Run `check-source-table-has-description` hook

**Expected behavior**
Empty/invalid YML files are skipped.

**Version:**
v1,0.0

**Comment by tomsej** [comment]
I am unable to reproduce this bug. Doesn't look your YAML like this:

```
version: 2

sources:
```

**Comment by stumelius** [comment]
@tomsej I meant a completely empty file, no yml properties at all. Sorry, i should have been more clear.

**Comment by JFrackson** [comment]
I can verify that this is still an issue and reproduced on dbt-checkpoint 1.1.0. It is an edge case, however, so I think it's relatively low priority for now.

**Comment by kaveri-lolge** [comment]
Hello everyone, 

I'm facing a similar issue but not for version 1.1.0.  For v1.1.0, the pre-commit run is stuck forever on the hook like in below screenshot
<img width="633" alt="image" src="https://github.com/dbt-checkpoint/dbt-checkpoint/assets/55696896/3f8069b8-4745-4f67-b9b1-96c511d284dc">

However, for version 1.1.1 and 1.0.0, I get the similar error for `Check the model columns have description` as @stumelius  and `Check the model has description` doesn't work like mentioned above.
```
Check the model columns have description.................................Failed
- hook id: check-model-columns-have-desc
- exit code: 1

Traceback (most recent call last):
  File "/Users/kaveri.lolge/.cache/pre-commit/repo6d965u6z/py_env-python3/bin/check-model-columns-have-desc", line 8, in <module>
    sys.exit(main())
  File "/Users/kaveri.lolge/.cache/pre-commit/repo6d965u6z/py_env-python3/lib/python3.9/site-packages/dbt_checkpoint/check_model_columns_have_desc.py", line 90, in main
    status_code, _ = check_column_desc(paths=args.filenames, manifest=manifest)
  File "/Users/kaveri.lolge/.cache/pre-commit/repo6d965u6z/py_env-python3/lib/python3.9/site-packages/dbt_checkpoint/check_model_columns_have_desc.py", line 38, in check_column_desc
    for item in itertools.chain(models, schemas):
  File "/Users/kaveri.lolge/.cache/pre-commit/repo6d965u6z/py_env-python3/lib/python3.9/site-packages/dbt_checkpoint/utils.py", line 218, in get_model_schemas
    for model in schema.get("models", []):
AttributeError: 'NoneType' object has no attribute 'get'

Check the model has description..........................................
```

**Comment by noel** [comment]
Why would we want to skip an empty file. Seems to be an error IMO. either you have a file with keys and values or no file at all no?

Maybe we can fail more gracefully, but IMO this is an accurate error the model does not have descriptions.

**Comment by kaveri-lolge** [comment]
Hi @noel, last week when I was running pre-commit, I was getting below error for models not having description, and IMO this looks more appropriate 
```
Check the model has description..........................................Failed
- hook id: check-model-has-description
- exit code: 1

models/staging/cms/base/stg_cms__feed_item_languages.sql: does not have defined description or properties file is missing.
analysis/ott/ott__matchday_categorized_users.sql: does not have defined description or properties file is missing.
analysis/series_d/series_d__month_return_rates.sql: does not have defined description or properties file is missing.
```

similarly, for columns not having description I got below
```
Check the model columns have description.................................Failed
- hook id: check-model-columns-have-desc
- exit code: 1

models/staging/betting/stg_betting__odds.sql: following columns are missing description:
- kickoff_time
models/staging/scores/stg_scores__seasons.sql: following columns are missing description:
- id_division
- updated
- manually
- name
- is_active
- id
```

**Comment by robertnajmik** [comment]
Hi, @kaveri-lolge , @noel, I'm also dealing with a similar inconsistency when using the dbt-checkpoint. (running v2.0.1)

While running the hook id: check-model-columns-have-desc I get the following error:
`AttributeError: 'NoneType' object has no attribute 'get'`

Right after that I run the hook id: check-column-desc-are-same and it works allright.

Is there anything on my end that can solve this problem? Thanks a lot.

**Comment by k0x2e** [comment]
This was fixed in the v2.x rewrite. `checkpoint_safe_load` in `utils.py` uses `safe_load(stream) or {}`, so empty or whitespace-only YAML files return an empty dict instead of `None`, and callers iterating `schema.get('sources', [])` get an empty list rather than an `AttributeError`. Closing as resolved.
